Add description to posts
MaxLeiter/Drift pull request #71
Opened 2022-04-04 20:11 UTC by jazcarate

Closes #37

I'm very bad at frontend😅. I'd love some feedback on the description look

## List
![image](https://user-images.githubusercontent.com/403456/161623062-119a313b-5fe9-4a01-a057-df4389baa874.png)

## Creation
This is very bad 😂 
![image](https://user-images.githubusercontent.com/403456/161623900-75c4bd7a-f0a5-4160-b018-b4b719ead576.png)

## Show
![image](https://user-images.githubusercontent.com/403456/161623219-e8525422-eba9-454b-9fa8-f3a9c42720d0.png)

2022-04-05 00:29 UTC, MaxLeiter requested changes

2022-04-05 00:29 UTC, MaxLeiter commented on client/components/new-post/description/index.tsx
> +                width="100%"
can you run + commit `yarn lint` in client/?

2022-04-05 00:32 UTC, MaxLeiter commented
This is great! What are your thoughts on using an `<Input />` for the description to encourage keeping it on the shorter side? I envision descriptions being one sentence max, but maybe you have a different vision; I don't care a lot either way but my way may simplify the design.

2022-04-05 16:47 UTC, jazcarate commented
I like the `<Input>` 😸 
![image](https://user-images.githubusercontent.com/403456/161805640-4ca57873-21e6-4016-b1ce-d5e1ea1836a0.png)

2022-04-06 16:09 UTC, MaxLeiter commented
Sorry @jazcarate, happy to merge this but the migration is `08_` now; I merged #25

2022-04-06 17:25 UTC, MaxLeiter requested changes

2022-04-06 17:25 UTC, MaxLeiter commented on client/components/new-post/description/index.tsx
> +			<Input
can we set the max length to 256? that's the same as Gist.

2022-04-06 17:25 UTC, MaxLeiter commented on server/src/routes/posts.ts
> +			description: Joi.string().optional(),
```js       
Joi.string().optional()
    .min(0)
    .max(256)
```

2022-04-06 17:25 UTC, MaxLeiter commented on server/src/routes/posts.ts
> +			description: Joi.string().optional(),
```js       
Joi.string().optional()
    .min(0)
    .max(256)
```

2022-04-14 00:44 UTC, MaxLeiter commented
whoops, sorry for the delay on this @jazcarate. I think it's all set if you can fix the conflicts (again, sorry... I'm done with major changes for a little bit d:)

2022-04-14 21:16 UTC, jazcarate commented
There! no more conflicts 😸

2022-04-14 21:25 UTC, merged